import { Agent } from "@/types";

export const defaultAgents: Agent[] = [
  {
    id: "ek-orch",
    name: "ek-orch",
    division: "learning",
    model: "opus-5",
    status: "active",
    currentTask: "Coordinating HeyOmmi OAuth integration",
    machineId: "macmini-dev",
    skills: ["orchestration", "planning", "delegation"],
  },
  {
    id: "ek-eng",
    name: "ek-eng",
    division: "engineering",
    model: "sonnet-5",
    status: "active",
    currentTask: "Reviewing API design",
    skills: ["architecture", "code-review", "technical-lead"],
  },
  {
    id: "ek-dev",
    name: "ek-dev",
    division: "engineering",
    model: "sonnet-5",
    status: "active",
    currentTask: "Implementing OAuth endpoint",
    machineId: "macmini-dev",
    skills: ["full-stack-dev", "features", "bug-fixes"],
  },
  {
    id: "ek-ui",
    name: "ek-ui",
    division: "creative",
    model: "sonnet-5",
    status: "active",
    currentTask: "Building login form UI",
    machineId: "macmini-dev",
    skills: ["ui-components", "responsive", "accessibility"],
  },
  {
    id: "ek-creative",
    name: "ek-creative",
    division: "creative",
    model: "fable-5",
    status: "idle",
    skills: ["creative-direction", "design", "branding"],
  },
  {
    id: "ek-brand",
    name: "ek-brand",
    division: "creative",
    model: "fable-5",
    status: "idle",
    skills: ["branding", "copywriting", "marketing"],
  },
  {
    id: "ek-motion",
    name: "ek-motion",
    division: "creative",
    model: "sonnet-5",
    status: "idle",
    skills: ["animations", "motion-design", "transitions"],
  },
  {
    id: "ek-api",
    name: "ek-api",
    division: "engineering",
    model: "codex",
    status: "idle",
    skills: ["api-design", "endpoints", "rest-graphql"],
  },
  {
    id: "ek-db",
    name: "ek-db",
    division: "engineering",
    model: "sonnet-5",
    status: "idle",
    skills: ["database-design", "migrations", "queries"],
  },
  {
    id: "ek-ops",
    name: "ek-ops",
    division: "operations",
    model: "sonnet-5",
    status: "active",
    currentTask: "Monitoring deployment pipeline",
    skills: ["operations", "workflows", "automation"],
  },
  {
    id: "ek-git",
    name: "ek-git",
    division: "operations",
    model: "codex",
    status: "idle",
    skills: ["git", "branching", "commits"],
  },
  {
    id: "ek-deploy",
    name: "ek-deploy",
    division: "operations",
    model: "codex",
    status: "active",
    currentTask: "Deploying v2.1.0 to staging",
    machineId: "macmini-build",
    skills: ["deployment", "infrastructure", "ci-cd"],
  },
  {
    id: "ek-qa",
    name: "ek-qa",
    division: "operations",
    model: "sonnet-5",
    status: "idle",
    skills: ["testing", "quality", "debugging"],
  },
  {
    id: "ek-learning",
    name: "ek-learning",
    division: "learning",
    model: "opus-5",
    status: "idle",
    skills: ["research", "learning", "knowledge-ingestion"],
  },
];
